#!/usr/bin/env bash
# "vmctl" that can: create a VM from a cloud image (QCOW2) with cloud-init, 
# take/delete snapshots, perform live migration to a target hypervisor, 
# list VM status, and batch-start/stop VMs from a hosts file. 
# include checks for required tools, argument parsing, idempotency, 
# and logging to /var/log/vmctl.log.
set -euo pipefail

LOG="/var/log/vmctl.log"
IMG_DIR="/var/lib/libvirt/images"
CLOUD_IMG="/var/lib/libvirt/images/ubuntu-22.04-server-cloudimg-amd64.img"
POOL="default"
DRY_RUN=0

log(){ echo "$(date --iso-8601=seconds) $*" >> "$LOG"; }

usage(){
  cat <<USAGE
Usage: $0 create <vmname> <cpus> <ram_mb> <disk_gb> <ssh_pubkey>
       $0 snapshot <vmname> <snapname>
       $0 snapshot-delete <vmname> <snapname>
       $0 migrate <vmname> <target_host>
       $0 list
       $0 start <vmname>
       $0 stop <vmname>
USAGE
  exit 1
}

require_tools(){
  for t in virsh virt-install qemu-img cloud-localds; do
    command -v "$t" >/dev/null 2>&1 || { echo "Missing $t"; exit 2; }
  done
}

create_vm(){
  vm="$1"; cpus="$2"; ram="$3"; disk_gb="$4"; ssh_key="$5"
  disk_path="${IMG_DIR}/${vm}.qcow2"
  cloud_iso="${IMG_DIR}/${vm}-cidata.iso"
  if virsh dominfo "$vm" >/dev/null 2>&1; then
    log "VM $vm already exists; skipping create"
    return
  fi
  log "Creating disk for $vm at $disk_path"
  if [ "$DRY_RUN" -eq 0 ]; then
    qemu-img create -f qcow2 -b "$CLOUD_IMG" "$disk_path" "${disk_gb}G"
    # prepare cloud-init ISO
    tmpdir=$(mktemp -d)
    cat > "$tmpdir/user-data" <<EOF
#cloud-config
ssh_authorized_keys:
  - $ssh_key
hostname: $vm
EOF
    echo "Instance generated by vmctl" > "$tmpdir/meta-data"
    cloud-localds -v "$cloud_iso" "$tmpdir/user-data" "$tmpdir/meta-data"
    rm -rf "$tmpdir"
    virt-install --name "$vm" --ram "$ram" --vcpus "$cpus" \
      --disk "path=${disk_path},format=qcow2" \
      --disk "path=${cloud_iso},device=cdrom" \
      --os-variant ubuntu22.04 --import --noautoconsole --network network=default
  else
    log "DRY-RUN: would create $vm"
  fi
  log "Create completed for $vm"
}

snapshot_vm(){
  vm="$1"; snap="$2"
  if [ "$DRY_RUN" -eq 1 ]; then
    log "DRY-RUN: would snapshot $vm as $snap"
    return
  fi
  virsh snapshot-create-as --domain "$vm" --name "$snap" --atomic --disk-only --quiesce
  log "Snapshot $snap created for $vm"
}

delete_snapshot(){
  vm="$1"; snap="$2"
  virsh snapshot-delete --domain "$vm" --snapshotname "$snap"
  log "Snapshot $snap deleted for $vm"
}

migrate_vm(){
  vm="$1"; target="$2"
  # ensure running or paused; use live migration
  if [ "$DRY_RUN" -eq 1 ]; then
    log "DRY-RUN: would migrate $vm to $target"
    return
  fi
  virsh migrate --live --persistent --undefinesource --verbose "$vm" "qemu+ssh://${target}/system" || {
    log "Migration failed for $vm to $target"; return 1
  }
  log "Migrated $vm to $target"
}

main(){
  require_tools
  cmd="${1:-}"
  case "$cmd" in
    create) create_vm "$2" "$3" "$4" "$5" "$6" ;;
    snapshot) snapshot_vm "$2" "$3" ;;
    snapshot-delete) delete_snapshot "$2" "$3" ;;
    migrate) migrate_vm "$2" "$3" ;;
    list) virsh list --all ;;
    start) virsh start "$2"; log "Started $2" ;;
    stop) virsh shutdown "$2"; log "Stopped $2" ;;
    *) usage ;;
  esac
}

main "$@"
